{% set version = "10.86.46" %}

package:
  name: netpbm
  version: {{ version }}

source:
  url: https://downloads.sourceforge.net/project/netpbm/super_stable/{{ version }}/netpbm-{{ version }}.tgz
  sha256: 743729a0cdbfe502140e87789cc54f864c7a97f019ca1ade883199cec1e638d2

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - pkg-config
    - flex
    - ghostscript
    - gettext
    - make
    - sed
  host:
    - perl
    - libjpeg-turbo
    - libtiff
    - zlib
    - libpng
    - libxml2
    - xorg-kbproto
    - xorg-libx11
    - xorg-xproto
  run:
    - perl

test:
  commands:
    - pnmtopng -version
    - pnmtops -version
    - ppmtogif -version
    - pamscale -version
    - tifftopnm -version
    - jpegtopnm -version
    - ppmtopgm -version
    - pamcut -version
    - bmptopnm -version

about:
  home: http://netpbm.sourceforge.net
  license: OTHER
  license_file: doc/copyright_summary
  summary: Netpbm is a toolkit for manipulation of graphic images, including conversion of images between a variety of different formats.
  doc_url: http://netpbm.sourceforge.net/doc/
  dev_url: http://svn.code.sf.net/p/netpbm/code/

extra:
  recipe-maintainers:
    - danielnachun
    - juliotux
