travis:
  secure:
    BINSTAR_TOKEN: 0+/wDbO3ukY6C7vuLZ1lsQZGBSG31uuRLNfh1X2wvp8nHwFcVnBQfQmCi0X5S4re74t7xB1Lm8xLz9BMklE4M1sGdOKWO1Xz9xeZpCkZvLsMvXEXKVZgsc4nYFDfeHmn0mY0w7PzgIbsO4drq7LEV8X/1avqZuDZ9UQDlHdtL5S12/nU/CUEehN6d7U5YpHvoTf2idwAZbHTV3oWAjDK8pAk0PRdDJxKOFsa4F64nOmaR5kYnG3sxB9JnXpgpQhJAPJ+nXKqKKjt1nMSOs+idIw0MZE38pktErtVU0mMGDnOgdm4tmBcafiJVWo6wddwuMVY5iZ0oyEVDlHszGGMXm1jNbP9Yrn6WFzLnivwOs5m9LPPW5pbw1Q9EYhPT79LcL3if0IOHmbKW92fW4UapxVb0ejNhg6Y5R33sSYG6nGnCcFFLPPFKM4iQYvx7L5oztUPa4O5RYsYYboIiH+aC2RG18ghX7aZY8FzhFOMqdDsDC4iSpCcj7Gk09rSYenDcd4xKFIijfLg67XOW0faOeRBDZJxa2Nuuy0uJw2G+0e3iHnzOS7rmjUPAMAYvFnhHnBGM41gCmS4SL5iGOW+fKHBe5hZAdFFJe86pw8b/WctXW0Ky1UglMXoDs+KvtSJNITiqzZTIr+p8KJZJMjgLeh9mNeueHAwckzY9yG7eBU=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
